### ISSUE TITLE
Install / Prerequisite Instructions Need More Detail

### ISSUE THREAD

**Issue by markrittman** [LukaFontanilla/looker-explore-assistant#6]
Hi,

The install instructions in the readme file don't work unless, I suspect, the reader has all of the development software already pre-installed that Luka has on his development workstation.

For example, running them on my Mac (Sonoma 14.3 with Intel CPU):

1. `git clone git@github.com:LukaFontanilla/looker-explore-assistant.git`

gives the error message: `"Cloning into 'looker-explore-assistant'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."`

and instead I have to use `git clone https://github.com/LukaFontanilla/looker-explore-assistant.git`

2. The steps that use Terraform e.g. `terraform init`, `terraform apply` etc need Terraform to be first installed, which on my Mac needs me to run:

```
brew tap hashicorp/tap
brew install hashicorp/tap/terraform
```

which then errors unless I've run `brew install gcc`, which then requires me to run `xcode-select --install` .. etc etc

Could you either (1) update the install instructions to either list-out what needs to be installed to make the development environment sufficient to then run you instructions, correcting the git step so that it works without a private/public key, or (2) is there a way you can pre-build the code, as has been done with the other Gen AI Extension Framework example that's available for Looker that include another take on natural-language querying of Looker explores?

Btw - great work on this example and thanks for making it available ;-)

Mark

**Comment by LukaFontanilla** [comment]
Hey Mark - thank you for the callout on the pre-requisites. Yes, a git ssh-config, npm & terraform and/or gcloud installed are required to deploy this extension. We can make an update to link to the relevant documentation to be followed depending on the OS type.

RE: bundling the Extension source code. I would love to have this pre-bundled, but there are a few ways the extension is configured that will prevent that:

1. The extension is setup to be deployed and trained on one explore at a time.
2. The extension has starter queries that are categorized for a given use case, this will need to be swapped for the dataset connected.
3. The extension follows a database agnostic approach, by deploying the LLM integration as a separate API and not in the database layer and that API endpoint URL we can't anticipate ahead of time.

On this note, we've considered adding a command line package that guides the user through deployment of resources with customization per deployment. That could be something we can look into again.

Your feedback is appreciated!

**Comment by LukaFontanilla** [comment]
We've added a few new enhancements in the latest release. Namely documentation additions (pre-requisites in each step, optional install via cloud shell, and a BQ deployment version). Thanks for the feedback in helping us improve the solution!

**Comment by markrittman** [comment]
Excellent, I'll take a look through it and provide feedback if there's any remaining challenges - thanks!
