### ISSUE TITLE
Error in connection name

### ISSUE THREAD

**Issue by markrittman** [LukaFontanilla/looker-explore-assistant#8]
In step 6 of the BigQuery Deployment set of instructions, the step tells you to run the following DDL:

```
CREATE OR REPLACE MODEL
    `PROJECT_ID.DATASET_ID.explore_assistant_llm`
    REMOTE WITH CONNECTION `PROJECT_ID.REGION.explore_assistant`
    OPTIONS (ENDPOINT = 'gemini-pro');
```

but the connection name should be `PROJECT_ID.REGION.explore_assistant_llm` - I think the connection name and dataset name you define in the next step got mixed-up here?

**Comment by LukaFontanilla** [comment]
Hey Mark, thanks for flagging this. A new version was deployed to update the docs regarding this.
